### ISSUE TITLE
Question: Does this make any modifications to the source project?

### ISSUE THREAD

**Issue by TravisEz13** [pmiossec/TotalTfsMigrationTool#1]

**Comment by pmiossec** [comment]
Yes, you could have a look at the history of commits...

I have:
- Added support of Folded tfs Interation paths 
- Improved workitems matching
- Improves a little the logging
- Fixed a bug where importing areas filled Iterations instead of areas :(
- Added the support of Iterations StartDate and FinishDate

and in the `force_creation` branch, there is also a began of support of "never fail" import where every workitem is imported even if I should set some false values (because older ones are no more permitted --a user no more existing for example--). This to be sure that all the workitems are imported (otherwise some important workitems could be missing)
